/*
объект с действиями
на каждый запрос 
*/
const ACTION_TYPES = {
  CREATE_HERO_REQUEST: "CREATE_HERO_REQUEST",
  CREATE_HERO_SUCCESS: "CREATE_HERO_SUCCESS",
  CREATE_HERO_ERROR: "CREATE_HERO_ERROR",

  GET_HERO_REQUEST: "GET_HERO_REQUEST",
  GET_HERO_SUCCESS: "GET_HERO_SUCCESS",
  GET_HERO_ERROR: "GET_HERO_ERROR",
};

export default ACTION_TYPES;
